import "server-only";
import type {DeliveryStatus,EmailType,PrismaClient} from "@prisma/client";
import {authorizeWorkspace} from "./authorization";

export type EmailInput={workspaceId?:string;recipientUserId?:string;to:string;subject:string;body:string;actionUrl?:string;type:EmailType};
export interface EmailProvider{queue(input:EmailInput):Promise<{id:string}>;deliver(id:string,simulateFailure?:boolean):Promise<{status:DeliveryStatus}>;retry(id:string):Promise<{status:DeliveryStatus}>}
export class DevelopmentOutboxProvider implements EmailProvider{constructor(private db:PrismaClient){}async queue(input:EmailInput){return this.db.developmentEmail.create({data:{workspaceId:input.workspaceId,recipientUserId:input.recipientUserId,toAddress:input.to.toLowerCase(),subject:input.subject,previewBody:input.body,actionUrl:input.actionUrl,type:input.type},select:{id:true}})}async deliver(id:string,simulateFailure=false){return this.db.developmentEmail.update({where:{id},data:simulateFailure?{status:"FAILED",attempts:{increment:1},failureReason:"Simulated development delivery failure"}:{status:"DELIVERED",attempts:{increment:1},failureReason:null,deliveredAt:new Date()},select:{status:true}})}async retry(id:string){await this.db.developmentEmail.update({where:{id},data:{status:"PENDING",failureReason:null}});return this.deliver(id)}}
export async function listDevelopmentEmails(db:PrismaClient,userId:string,workspaceId:string){if(!await authorizeWorkspace(db,userId,workspaceId,"OWNER"))throw new Error("Development outbox access denied");return db.developmentEmail.findMany({where:{workspaceId},orderBy:{createdAt:"desc"},take:100})}
export async function retryDevelopmentEmail(db:PrismaClient,userId:string,workspaceId:string,id:string){if(!await authorizeWorkspace(db,userId,workspaceId,"OWNER"))throw new Error("Development outbox access denied");const email=await db.developmentEmail.findFirst({where:{id,workspaceId}});if(!email)throw new Error("Email preview not found");return new DevelopmentOutboxProvider(db).retry(id)}
