import "dotenv/config";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@prisma/client"; import { PrismaPg } from "@prisma/adapter-pg";
import { createArticle, createUpload, deleteDocument, getDocument, KnowledgeAccessDenied, retryDocument, updateArticle } from "./knowledge-service";
import type { PrivateStorage } from "./storage";

class MemoryStorage implements PrivateStorage { files = new Map<string,Buffer>(); deleted:string[]=[]; async put(workspaceId:string,extension:string,data:Buffer){const key=`${workspaceId}/safe.${extension}`;this.files.set(key,data);return key} async read(key:string){const value=this.files.get(key);if(!value)throw new Error("Missing file");return value} async delete(key:string){this.deleted.push(key);this.files.delete(key)} }
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL!})}), marker=`m4-${Date.now()}-${Math.random().toString(36).slice(2)}`; let workspaceId="",otherWorkspaceId="",ownerId="",agentId="",viewerId="";
beforeAll(async()=>{const [workspace,other]=await Promise.all([db.workspace.create({data:{name:marker,slug:marker}}),db.workspace.create({data:{name:`${marker}-other`,slug:`${marker}-other`}})]);workspaceId=workspace.id;otherWorkspaceId=other.id;const users=await Promise.all([...["owner","agent","viewer"].map((name,i)=>db.user.create({data:{name,email:`${marker}-${name}@example.test`,passwordHash:"test",memberships:{create:{workspaceId,role:["OWNER","AGENT","VIEWER"][i] as "OWNER"|"AGENT"|"VIEWER"}}}}))]);[ownerId,agentId,viewerId]=users.map(u=>u.id)});
afterAll(async()=>{await db.workspace.deleteMany({where:{id:{in:[workspaceId,otherWorkspaceId]}}});await db.user.deleteMany({where:{email:{startsWith:marker}}});await db.$disconnect()});
describe("knowledge authorization and lifecycle",()=>{
  it("allows agents to create and edit ordered article chunks",async()=>{const article=await createArticle(db,agentId,workspaceId,{title:"Agent guide",content:"A".repeat(1300)});const detail=await getDocument(db,viewerId,workspaceId,article.id);expect(detail?.chunks.map(c=>c.position)).toEqual([0,1]);await updateArticle(db,agentId,workspaceId,article.id,{title:"Updated guide",content:"Updated content"});expect((await getDocument(db,viewerId,workspaceId,article.id))?.title).toBe("Updated guide")});
  it("rejects viewer mutations and cross-workspace access",async()=>{await expect(createArticle(db,viewerId,workspaceId,{title:"Forbidden",content:"No"})).rejects.toBeInstanceOf(KnowledgeAccessDenied);const article=await createArticle(db,ownerId,workspaceId,{title:"Private",content:"Workspace only"});await expect(getDocument(db,ownerId,otherWorkspaceId,article.id)).rejects.toBeInstanceOf(KnowledgeAccessDenied);await expect(deleteDocument(db,new MemoryStorage(),agentId,workspaceId,article.id)).rejects.toBeInstanceOf(KnowledgeAccessDenied)});
  it("processes uploads, deletes storage, and retries failures",async()=>{const storage=new MemoryStorage();const text=Buffer.from("Useful support knowledge");const uploaded=await createUpload(db,storage,agentId,workspaceId,{title:"Text guide",originalFilename:"guide.txt",mimeType:"text/plain",size:text.length,extension:"txt",sourceType:"TXT",data:text});expect(uploaded.status).toBe("READY");expect((await getDocument(db,viewerId,workspaceId,uploaded.id))?.chunks[0].content).toContain("Useful");await deleteDocument(db,storage,ownerId,workspaceId,uploaded.id);expect(storage.deleted).toHaveLength(1);const bad=Buffer.from("%PDF-broken");const failed=await createUpload(db,storage,agentId,workspaceId,{title:"Bad PDF",originalFilename:"bad.pdf",mimeType:"application/pdf",size:bad.length,extension:"pdf",sourceType:"PDF",data:bad});expect(failed.status).toBe("FAILED");await expect(retryDocument(db,storage,agentId,workspaceId,failed.id)).rejects.toThrow(/corrupted|encrypted|unsupported/);expect((await getDocument(db,viewerId,workspaceId,failed.id))?.jobs.length).toBeGreaterThan(1)});
});
