import type { PrismaClient, ProcessingStatus } from "@prisma/client";
import { authorizeWorkspace } from "./authorization";
import { articleChunks, extractDocument, type SourceType } from "./document-processing";
import type { PrivateStorage } from "./storage";
export class KnowledgeAccessDenied extends Error{}
async function access(db:PrismaClient,userId:string,workspaceId:string,write=false,owner=false){const membership=await authorizeWorkspace(db,userId,workspaceId,owner?"OWNER":write?"AGENT":"VIEWER");if(!membership)throw new KnowledgeAccessDenied("Knowledge Base access denied");return membership}
async function scoped(db:PrismaClient,userId:string,workspaceId:string,id:string,write=false,owner=false){await access(db,userId,workspaceId,write,owner);const document=await db.knowledgeDocument.findFirst({where:{id,workspaceId}});if(!document)throw new KnowledgeAccessDenied("Document not found");return document}
export async function listDocuments(db:PrismaClient,userId:string,workspaceId:string,input:{page?:number;query?:string;collectionId?:string;status?:ProcessingStatus}){await access(db,userId,workspaceId);const page=Math.max(1,input.page??1),take=10,where={workspaceId,...(input.query?{OR:[{title:{contains:input.query,mode:"insensitive" as const}},{description:{contains:input.query,mode:"insensitive" as const}},{originalFilename:{contains:input.query,mode:"insensitive" as const}}]}:{}),...(input.collectionId?{collectionId:input.collectionId}:{}),...(input.status?{status:input.status}:{})};const [items,total]=await Promise.all([db.knowledgeDocument.findMany({where,include:{collection:true,creator:true,_count:{select:{chunks:true}}},orderBy:{updatedAt:"desc"},skip:(page-1)*take,take}),db.knowledgeDocument.count({where})]);return{items,total,page,pages:Math.max(1,Math.ceil(total/take))}}
export async function getDocument(db:PrismaClient,userId:string,workspaceId:string,id:string){await scoped(db,userId,workspaceId,id);return db.knowledgeDocument.findFirst({where:{id,workspaceId},include:{collection:true,creator:true,chunks:{orderBy:{position:"asc"}},jobs:{orderBy:{createdAt:"desc"},take:5},activities:{include:{actor:true},orderBy:{createdAt:"desc"},take:20}}})}
export async function createArticle(db:PrismaClient,userId:string,workspaceId:string,input:{title:string;description?:string;content:string;collectionId?:string}){await access(db,userId,workspaceId,true);if(input.collectionId&&!await db.knowledgeCollection.findFirst({where:{id:input.collectionId,workspaceId}}))throw new KnowledgeAccessDenied("Collection not found");const chunks=articleChunks(input.content);return db.$transaction(async tx=>{const document=await tx.knowledgeDocument.create({data:{workspaceId,creatorId:userId,collectionId:input.collectionId||null,title:input.title,description:input.description,sourceType:"ARTICLE",status:"READY",chunks:{create:chunks.map((chunk,position)=>({...chunk,position}))}}});await tx.documentActivity.create({data:{workspaceId,documentId:document.id,actorId:userId,type:"article.created",description:`Created article “${input.title}”`}});return document})}
export async function createUpload(db:PrismaClient,storage:PrivateStorage,userId:string,workspaceId:string,input:{title:string;description?:string;collectionId?:string;originalFilename:string;mimeType:string;size:number;extension:string;sourceType:SourceType;data:Buffer}){await access(db,userId,workspaceId,true);if(input.collectionId&&!await db.knowledgeCollection.findFirst({where:{id:input.collectionId,workspaceId}}))throw new KnowledgeAccessDenied("Collection not found");const storageKey=await storage.put(workspaceId,input.extension,input.data);let document;try{document=await db.$transaction(async tx=>{const created=await tx.knowledgeDocument.create({data:{workspaceId,creatorId:userId,collectionId:input.collectionId||null,title:input.title,description:input.description,sourceType:input.sourceType,originalFilename:input.originalFilename,mimeType:input.mimeType,fileSize:input.size,storageKey,status:"PENDING"}});await tx.processingJob.create({data:{workspaceId,documentId:created.id,status:"PENDING"}});await tx.documentActivity.create({data:{workspaceId,documentId:created.id,actorId:userId,type:"document.uploaded",description:`Uploaded ${input.originalFilename}`}});return created})}catch(error){await storage.delete(storageKey);throw error}try{await processDocument(db,storage,userId,workspaceId,document.id)}catch{}return db.knowledgeDocument.findUniqueOrThrow({where:{id:document.id}})}
export async function processDocument(db:PrismaClient,storage:PrivateStorage,userId:string,workspaceId:string,id:string){const document=await scoped(db,userId,workspaceId,id,true);if(!document.storageKey||document.sourceType==="ARTICLE")throw new Error("This document does not have an uploaded source");const job=await db.processingJob.create({data:{workspaceId,documentId:id,status:"PROCESSING",attempts:1,startedAt:new Date()}});await db.knowledgeDocument.update({where:{id},data:{status:"PROCESSING",failureReason:null}});try{const data=await storage.read(document.storageKey),chunks=await extractDocument(document.sourceType as SourceType,data);await db.$transaction([db.documentChunk.deleteMany({where:{documentId:id}}),db.documentChunk.createMany({data:chunks.map((chunk,position)=>({documentId:id,position,content:chunk.content,pageNumber:chunk.pageNumber,section:chunk.section,metadata:chunk.metadata}))}),db.knowledgeDocument.update({where:{id},data:{status:"READY",failureReason:null}}),db.processingJob.update({where:{id:job.id},data:{status:"READY",completedAt:new Date()}}),db.documentActivity.create({data:{workspaceId,documentId:id,actorId:userId,type:"document.processed",description:`Processed ${chunks.length} text chunks`}})]);return chunks}catch(error){const reason=error instanceof Error?error.message:"Document processing failed";await db.$transaction([db.knowledgeDocument.update({where:{id},data:{status:"FAILED",failureReason:reason}}),db.processingJob.update({where:{id:job.id},data:{status:"FAILED",failureReason:reason,completedAt:new Date()}}),db.documentActivity.create({data:{workspaceId,documentId:id,actorId:userId,type:"document.failed",description:reason}})]);throw new Error(reason)}}
export async function updateArticle(db:PrismaClient,userId:string,workspaceId:string,id:string,input:{title:string;description?:string;content?:string;collectionId?:string}){const document=await scoped(db,userId,workspaceId,id,true);if(input.collectionId&&!await db.knowledgeCollection.findFirst({where:{id:input.collectionId,workspaceId}}))throw new KnowledgeAccessDenied("Collection not found");const chunks=input.content===undefined?null:articleChunks(input.content);return db.$transaction(async tx=>{const updated=await tx.knowledgeDocument.update({where:{id},data:{title:input.title,description:input.description,collectionId:input.collectionId||null}});if(chunks){if(document.sourceType!=="ARTICLE")throw new Error("Uploaded document text cannot be edited");await tx.documentChunk.deleteMany({where:{documentId:id}});await tx.documentChunk.createMany({data:chunks.map((chunk,position)=>({documentId:id,position,content:chunk.content,section:chunk.section}))})}await tx.documentActivity.create({data:{workspaceId,documentId:id,actorId:userId,type:"document.updated",description:"Updated document details"}});return updated})}
export async function deleteDocument(db:PrismaClient,storage:PrivateStorage,userId:string,workspaceId:string,id:string){const document=await scoped(db,userId,workspaceId,id,false,true);await db.knowledgeDocument.delete({where:{id}});if(document.storageKey)await storage.delete(document.storageKey)}
export async function retryDocument(db:PrismaClient,storage:PrivateStorage,userId:string,workspaceId:string,id:string){const document=await scoped(db,userId,workspaceId,id,true);if(document.status!=="FAILED")throw new Error("Only failed documents can be retried");return processDocument(db,storage,userId,workspaceId,id)}
export async function createCollection(db:PrismaClient,userId:string,workspaceId:string,name:string,description?:string){await access(db,userId,workspaceId,true);return db.knowledgeCollection.create({data:{workspaceId,name,description}})}
