import type {Plan,PrismaClient} from "@prisma/client";
import {authorizeWorkspace} from "./authorization";
export const PLAN_LIMITS={FREE:{documents:10,members:3,conversations:100,aiRequests:100},PRO:{documents:100,members:15,conversations:2500,aiRequests:2000},BUSINESS:{documents:1000,members:100,conversations:25000,aiRequests:20000}} as const;
export const PLAN_LABELS={FREE:"Free",PRO:"Pro",BUSINESS:"Business"} as const;
export type LimitKind=keyof typeof PLAN_LIMITS.FREE;
export class PlanLimitError extends Error{}
export async function workspaceUsage(db:PrismaClient,workspaceId:string){const month=new Date();month.setUTCDate(1);month.setUTCHours(0,0,0,0);const [workspace,documents,memberCount,pendingInvitations,conversations,ai]=await Promise.all([db.workspace.findUniqueOrThrow({where:{id:workspaceId},select:{plan:true}}),db.knowledgeDocument.count({where:{workspaceId}}),db.membership.count({where:{workspaceId}}),db.invitation.count({where:{workspaceId,acceptedAt:null,expiresAt:{gt:new Date()}}}),db.conversation.count({where:{workspaceId,createdAt:{gte:month}}}),db.aIUsageEvent.aggregate({where:{workspaceId,createdAt:{gte:month}},_sum:{units:true}})]);return{plan:workspace.plan,documents,members:memberCount+pendingInvitations,activeMembers:memberCount,pendingInvitations,conversations,aiRequests:ai._sum.units??0,limits:PLAN_LIMITS[workspace.plan]}}
export async function enforcePlanLimit(db:PrismaClient,workspaceId:string,kind:LimitKind,increment=1){const usage=await workspaceUsage(db,workspaceId);if(usage[kind]+increment>usage.limits[kind])throw new PlanLimitError(`${PLAN_LABELS[usage.plan]} demonstration plan limit reached for ${kind}. An owner can change the demo plan in Billing.`);return usage}
export async function changePlan(db:PrismaClient,userId:string,workspaceId:string,toPlan:Plan){if(!await authorizeWorkspace(db,userId,workspaceId,"OWNER"))throw new Error("Only workspace owners can manage the demonstration plan");const current=await db.workspace.findUniqueOrThrow({where:{id:workspaceId},select:{plan:true}});if(current.plan===toPlan)return current;return db.$transaction(async tx=>{const updated=await tx.workspace.update({where:{id:workspaceId},data:{plan:toPlan}});await tx.subscriptionEvent.create({data:{workspaceId,actorId:userId,fromPlan:current.plan,toPlan,description:`Changed demonstration plan from ${PLAN_LABELS[current.plan]} to ${PLAN_LABELS[toPlan]}. No payment occurred.`}});return updated})}
