import type { ConversationPriority, ConversationStatus, PrismaClient } from "@prisma/client";
import { authorizeWorkspace } from "./authorization";
import {enforcePlanLimit} from "./plan-service";
export class AccessDenied extends Error {}
async function access(db:PrismaClient,userId:string,workspaceId:string,write=false){const m=await authorizeWorkspace(db,userId,workspaceId,write?"AGENT":"VIEWER");if(!m)throw new AccessDenied("Workspace access denied");return m}
async function conversation(db:PrismaClient,userId:string,workspaceId:string,id:string,write=false){await access(db,userId,workspaceId,write);const c=await db.conversation.findFirst({where:{id,workspaceId}});if(!c)throw new AccessDenied("Conversation not found");return c}
async function event(db:PrismaClient,workspaceId:string,conversationId:string|undefined,actorId:string,type:string,description:string,metadata?:Record<string,string>){return db.activityEvent.create({data:{workspaceId,conversationId,actorId,type,description,metadata}})}
export async function listConversations(db:PrismaClient,userId:string,workspaceId:string,input:{page?:number;query?:string;status?:ConversationStatus;priority?:ConversationPriority;assigneeId?:string;tagId?:string}){await access(db,userId,workspaceId);const page=Math.max(1,input.page??1),take=10;const where={workspaceId,...(input.query?{OR:[{subject:{contains:input.query,mode:"insensitive" as const}},{customer:{name:{contains:input.query,mode:"insensitive" as const}}},{customer:{email:{contains:input.query,mode:"insensitive" as const}}}]}:{}),...(input.status?{status:input.status}:{}),...(input.priority?{priority:input.priority}:{}),...(input.assigneeId==="unassigned"?{assignment:null}:input.assigneeId?{assignment:{agentId:input.assigneeId}}:{}),...(input.tagId?{tags:{some:{tagId:input.tagId}}}:{})};const [items,total]=await Promise.all([db.conversation.findMany({where,include:{customer:true,assignment:{include:{agent:true}},tags:{include:{tag:true}},messages:{orderBy:{createdAt:"desc"},take:1}},orderBy:{lastMessageAt:"desc"},skip:(page-1)*take,take}),db.conversation.count({where})]);return{items,total,page,pages:Math.max(1,Math.ceil(total/take))}}
export async function getConversation(db:PrismaClient,userId:string,workspaceId:string,id:string){await conversation(db,userId,workspaceId,id);return db.conversation.findFirst({where:{id,workspaceId},include:{customer:true,messages:{include:{user:true,customer:true},orderBy:{createdAt:"asc"}},assignment:{include:{agent:true}},tags:{include:{tag:true}},internalNotes:{include:{author:true},orderBy:{createdAt:"asc"}},activityEvents:{include:{actor:true},orderBy:{createdAt:"desc"},take:20}}})}
export async function createConversation(db:PrismaClient,userId:string,workspaceId:string,input:{name:string;email:string;subject:string;body:string;priority:ConversationPriority}){await access(db,userId,workspaceId,true);await enforcePlanLimit(db,workspaceId,"conversations");return db.$transaction(async tx=>{const customer=await tx.customer.upsert({where:{workspaceId_email:{workspaceId,email:input.email}},update:{name:input.name},create:{workspaceId,email:input.email,name:input.name}});const c=await tx.conversation.create({data:{workspaceId,customerId:customer.id,subject:input.subject,priority:input.priority,messages:{create:{authorType:"CUSTOMER",customerId:customer.id,body:input.body}}}});await event(tx as PrismaClient,workspaceId,c.id,userId,"conversation.created",`Created conversation “${input.subject}”`);return c})}
export async function addMessage(db:PrismaClient,userId:string,workspaceId:string,id:string,body:string,customer=false){const c=await conversation(db,userId,workspaceId,id,true);const m=await db.message.create({data:{conversationId:id,body,authorType:customer?"CUSTOMER":"AGENT",...(customer?{customerId:c.customerId}:{userId})}});await db.conversation.update({where:{id},data:{lastMessageAt:m.createdAt,status:customer?"OPEN":undefined}});await event(db,workspaceId,id,userId,customer?"message.customer":"message.agent",customer?"Added a customer message":"Replied to conversation");return m}
export async function updateConversation(db:PrismaClient,userId:string,workspaceId:string,id:string,data:{status?:ConversationStatus;priority?:ConversationPriority}){const c=await conversation(db,userId,workspaceId,id,true);const updated=await db.conversation.update({where:{id},data:{...data,resolvedAt:data.status==="RESOLVED"?new Date():data.status?null:undefined}});if(data.status&&data.status!==c.status)await event(db,workspaceId,id,userId,"conversation.status",`Changed status to ${data.status.toLowerCase()}`,{from:c.status,to:data.status});if(data.priority&&data.priority!==c.priority)await event(db,workspaceId,id,userId,"conversation.priority",`Changed priority to ${data.priority.toLowerCase()}`,{from:c.priority,to:data.priority});return updated}
export async function assignConversation(db:PrismaClient,userId:string,workspaceId:string,id:string,agentId?:string){await conversation(db,userId,workspaceId,id,true);if(!agentId){await db.assignment.deleteMany({where:{conversationId:id}});await event(db,workspaceId,id,userId,"conversation.unassigned","Unassigned conversation");return}const target=await authorizeWorkspace(db,agentId,workspaceId,"AGENT");if(!target)throw new AccessDenied("Assignee must be an owner or agent in this workspace");await db.assignment.upsert({where:{conversationId:id},update:{agentId,assignedById:userId},create:{conversationId:id,agentId,assignedById:userId}});await event(db,workspaceId,id,userId,"conversation.assigned",`Assigned conversation to ${target.userId}`)}
export async function setTag(db:PrismaClient,userId:string,workspaceId:string,id:string,tagId:string,remove=false){await conversation(db,userId,workspaceId,id,true);const tag=await db.tag.findFirst({where:{id:tagId,workspaceId}});if(!tag)throw new AccessDenied("Tag not found");if(remove)await db.conversationTag.deleteMany({where:{conversationId:id,tagId}});else await db.conversationTag.upsert({where:{conversationId_tagId:{conversationId:id,tagId}},update:{},create:{conversationId:id,tagId}});await event(db,workspaceId,id,userId,remove?"tag.removed":"tag.added",`${remove?"Removed":"Added"} tag ${tag.name}`)}
export async function addNote(db:PrismaClient,userId:string,workspaceId:string,id:string,body:string){await conversation(db,userId,workspaceId,id,true);const note=await db.internalNote.create({data:{conversationId:id,authorId:userId,body}});await event(db,workspaceId,id,userId,"note.added","Added an internal note");return note}
