import { cookies, headers } from "next/headers";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { getAIProvider } from "@/lib/ai/provider";
import { getOrCreateChatSession, getPublicChatbot } from "@/lib/ai/chatbot-service";
import { groundedAnswer } from "@/lib/ai/rag-service";
import { checkRateLimit, cleanInput } from "@/lib/ai/safety";

export async function POST(request:Request,{params}:{params:Promise<{publicId:string}>}){const {publicId}=await params,chatbot=await getPublicChatbot(db,publicId);if(!chatbot)return NextResponse.json({error:"Chatbot not found"},{status:404});const ip=(await headers()).get("x-forwarded-for")?.split(",")[0]??"local";try{checkRateLimit(`${publicId}:${ip}`);const question=cleanInput(z.object({question:z.string()}).parse(await request.json()).question);const store=await cookies(),cookieName=`sp_chat_${publicId.slice(0,8)}`,result=await getOrCreateChatSession(db,chatbot,store.get(cookieName)?.value);if(result.session.escalatedAt)return NextResponse.json({error:"A human agent has been requested. AI replies are paused."},{status:409});const customer=await db.conversation.findUniqueOrThrow({where:{id:result.session.conversationId},select:{customerId:true}});await db.message.create({data:{conversationId:result.session.conversationId,customerId:customer.customerId,authorType:"CUSTOMER",body:question}});const answer=await groundedAnswer(db,getAIProvider(),chatbot.workspaceId,question,{conversationId:result.session.conversationId});const message=await db.message.create({data:{conversationId:result.session.conversationId,authorType:"AI",aiGenerated:true,body:answer.answer}});await db.aIResponse.update({where:{id:answer.responseId},data:{messageId:message.id}});await db.conversation.update({where:{id:result.session.conversationId},data:{lastMessageAt:message.createdAt}});const encoder=new TextEncoder(),stream=new ReadableStream({async start(controller){for(const token of answer.answer.split(/(\s+)/)){controller.enqueue(encoder.encode(JSON.stringify({type:"token",value:token})+"\n"));await new Promise(resolve=>setTimeout(resolve,5))}controller.enqueue(encoder.encode(JSON.stringify({type:"done",answer:answer.answer,citations:answer.citations.map(({title,pageNumber,section,excerpt})=>({title,pageNumber,section,excerpt}))})+"\n"));controller.close()}});const response=new Response(stream,{headers:{"content-type":"application/x-ndjson; charset=utf-8","cache-control":"no-store"}});if(result.isNew)response.headers.append("set-cookie",`${cookieName}=${result.token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000`);return response}catch(error){const message=error instanceof Error?error.message:"AI is temporarily unavailable";return NextResponse.json({error:/unavailable|timed out|fetch/i.test(message)?"Our AI assistant is temporarily unavailable. Please try again or contact human support.":message},{status:503})}}
