import Link from "next/link";
import type { ProcessingStatus } from "@prisma/client";
import { BookOpen, FolderPlus, Upload } from "lucide-react";
import { createArticleAction, createCollectionAction, uploadDocumentAction } from "@/app/actions/knowledge";
import { PageHead } from "@/components/page-ui";
import { requireWorkspace } from "@/lib/auth";
import { db } from "@/lib/db";
import { MAX_UPLOAD_BYTES } from "@/lib/document-processing";
import { listDocuments } from "@/lib/knowledge-service";

export default async function KnowledgePage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const p = await searchParams; const { user, workspace, membership } = await requireWorkspace(); const page = Number(p.page) || 1;
  const [result, collections, ready] = await Promise.all([listDocuments(db, user.id, workspace.id, { page, query: p.q, collectionId: p.collection, status: p.status as ProcessingStatus | undefined }), db.knowledgeCollection.findMany({ where: { workspaceId: workspace.id }, orderBy: { name: "asc" } }), db.knowledgeDocument.count({ where: { workspaceId: workspace.id, status: "READY" } })]); const writable = membership.role !== "VIEWER";
  return <main className="page-wrap"><PageHead title="Knowledge Base" desc={`${result.total} sources in ${workspace.name}`} />{p.deleted && <div className="mb-4 rounded-xl border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-800">Document deleted securely.</div>}
    <div className="grid gap-4 md:grid-cols-3"><div className="metric-card"><div className="metric-top">Ready sources<BookOpen size={16}/></div><strong>{ready}</strong><span className="panel-sub">Available to your team</span></div><div className="metric-card"><div className="metric-top">Collections<FolderPlus size={16}/></div><strong>{collections.length}</strong><span className="panel-sub">Organized knowledge</span></div><div className="metric-card"><div className="metric-top">Upload limit<Upload size={16}/></div><strong>{MAX_UPLOAD_BYTES/1024/1024} MB</strong><span className="panel-sub">PDF, DOCX, and TXT</span></div></div>
    <section className="panel mt-4"><form className="grid gap-3 md:grid-cols-5"><input className="filter-input md:col-span-2" name="q" defaultValue={p.q} placeholder="Search title, description, or filename…"/><select className="filter-input" name="collection" defaultValue={p.collection}><option value="">All collections</option>{collections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select className="filter-input" name="status" defaultValue={p.status}><option value="">All statuses</option>{["PENDING","PROCESSING","READY","FAILED"].map(s=><option key={s}>{s}</option>)}</select><button className="btn-secondary">Apply filters</button></form></section>
    {writable && <div className="mt-4 grid gap-4 lg:grid-cols-2"><details className="panel"><summary className="cursor-pointer font-semibold">Upload a document</summary><form action={uploadDocumentAction} className="mt-5 grid gap-3"><input className="filter-input" name="title" required maxLength={200} placeholder="Document title"/><textarea className="filter-input" name="description" placeholder="Optional description"/><select className="filter-input" name="collectionId"><option value="">No collection</option>{collections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input className="filter-input" name="file" type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" required/><p className="text-xs text-[var(--muted)]">PDF, DOCX, or plain TXT only. Maximum 5 MB. Files are validated and stored privately.</p><button className="btn-primary">Upload and process</button></form></details>
      <details className="panel"><summary className="cursor-pointer font-semibold">Write a knowledge article</summary><form action={createArticleAction} className="mt-5 grid gap-3"><input className="filter-input" name="title" required maxLength={200} placeholder="Article title"/><textarea className="filter-input" name="description" placeholder="Optional description"/><select className="filter-input" name="collectionId"><option value="">No collection</option>{collections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><textarea className="filter-input min-h-48" name="content" required placeholder="Write the article…"/><button className="btn-primary">Create article</button></form></details>
      <details className="panel lg:col-span-2"><summary className="cursor-pointer font-semibold">Create collection</summary><form action={createCollectionAction} className="mt-5 flex flex-col gap-3 md:flex-row"><input className="filter-input flex-1" name="name" required placeholder="Collection name"/><input className="filter-input flex-1" name="description" placeholder="Description"/><button className="btn-secondary">Add collection</button></form></details></div>}
    <section className="panel mt-4">{result.items.length===0?<div className="empty-state"><div className="icon-box"><BookOpen size={21}/></div><h3>No knowledge found</h3><p>{writable?"Upload a supported document or write your first article.":"Your team has not published knowledge here yet."}</p></div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Source</th><th>Collection</th><th>Status</th><th>Chunks</th><th>Updated</th></tr></thead><tbody>{result.items.map(d=><tr key={d.id}><td><Link className="font-semibold text-[#6558f5]" href={`/dashboard/knowledge/${d.id}`}>{d.title}</Link><span className="block text-[var(--muted)]">{d.originalFilename??d.sourceType.toLowerCase()}</span></td><td>{d.collection?.name??"Unfiled"}</td><td><span className="badge">{d.status.toLowerCase()}</span></td><td>{d._count.chunks}</td><td>{d.updatedAt.toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section>
    <div className="mt-4 flex justify-between text-sm"><Link className={page<=1?"pointer-events-none opacity-40":"btn-secondary"} href={{query:{...p,page:page-1}}}>Previous</Link><span>Page {page} of {result.pages}</span><Link className={page>=result.pages?"pointer-events-none opacity-40":"btn-secondary"} href={{query:{...p,page:page+1}}}>Next</Link></div></main>;
}
