import Link from "next/link";
import { ArrowRight, Bot, Check, MessageSquare, ShieldCheck, Sparkles, Zap } from "lucide-react";
const features = [
  { icon: MessageSquare, title: "One intelligent inbox", text: "Bring every customer conversation together and keep your team perfectly in sync." },
  { icon: Bot, title: "Answers that improve", text: "Turn your help content into fast, consistent answers your customers can trust." },
  { icon: Zap, title: "Built for momentum", text: "Automate repetitive work and give agents the context to solve harder problems." },
];
export default function Home() { return <main className="min-h-screen overflow-hidden bg-[#f8f8fb] dark:bg-[#0b0d14]">
  <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href="/" className="brand"><span className="brand-mark"><Sparkles size={18}/></span>SupportPilot <b>AI</b></Link><div className="hidden items-center gap-8 text-sm text-slate-600 dark:text-slate-300 md:flex"><a href="#features">Product</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></div><div className="flex items-center gap-3"><Link className="btn-ghost hidden sm:inline-flex" href="/login">Log in</Link><Link className="btn-primary" href="/register">Start free <ArrowRight size={16}/></Link></div></nav>
  <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-16 text-center lg:px-8 lg:pt-24"><div className="hero-glow"/><div className="eyebrow"><Sparkles size={14}/> The support workspace built for modern teams</div><h1 className="relative mx-auto mt-6 max-w-4xl text-5xl font-semibold tracking-[-.045em] text-slate-950 dark:text-white md:text-7xl">Customer support that feels <span className="gradient-text">effortlessly human.</span></h1><p className="relative mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">SupportPilot helps growing teams resolve conversations faster, share knowledge, and understand what customers need—all in one calm workspace.</p><div className="relative mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link className="btn-primary h-12 px-6" href="/register">Start your free workspace <ArrowRight size={17}/></Link><Link className="btn-secondary h-12 px-6" href="/dashboard">View live dashboard</Link></div><p className="mt-4 text-xs text-slate-500">No credit card required · Set up in 2 minutes</p>
  <div className="hero-window"><div className="window-bar"><span/><span/><span/><em>app.supportpilot.ai</em></div><div className="demo-grid"><div className="demo-side"><div className="demo-logo"/><div className="demo-line active"/><div className="demo-line"/><div className="demo-line"/></div><div className="demo-main"><div className="demo-head"/><div className="grid gap-4 md:grid-cols-3"><div className="demo-card"><b>1,284</b><span>Conversations</span></div><div className="demo-card"><b>92%</b><span>Resolved</span></div><div className="demo-card"><b>4.9</b><span>CSAT score</span></div></div><div className="demo-chart">{[1,2,3,4,5,6,7,8,9,10].map(n=><i key={n}/>)}</div></div></div></div></section>
  <section id="features" className="bg-white py-24 dark:bg-[#10131d]"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="section-label">Everything in one place</p><h2 className="section-title">Give your team clarity. Give customers confidence.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map(({icon:Icon,title,text})=><article className="feature-card" key={title}><div className="icon-box"><Icon size={21}/></div><h3>{title}</h3><p>{text}</p><a href="#how">Learn more <ArrowRight size={15}/></a></article>)}</div></div></section>
  <section id="how" className="px-5 py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div><p className="section-label">A better way to support</p><h2 className="section-title">Less busywork. More helpful conversations.</h2><p className="mt-5 text-slate-600 dark:text-slate-300">SupportPilot brings your inbox, team knowledge, and insights into a workspace designed to keep everyone moving.</p><div className="mt-8 space-y-4">{["Unify customer conversations","Suggest consistent, trusted answers","Spot trends before they become problems"].map(x=><div className="check-row" key={x}><Check size={16}/>{x}</div>)}</div></div><div className="quote-card"><ShieldCheck size={28}/><p>“Our team spends less time searching and more time actually helping customers. SupportPilot made the whole operation feel lighter.”</p><div><b>Maya Chen</b><span>Head of Customer Experience, Northstar</span></div></div></div></section>
  <section id="pricing" className="mx-auto max-w-7xl px-5 pb-24"><div className="cta"><div><h2>Ready to make support your advantage?</h2><p>Join modern teams delivering faster, more thoughtful help.</p></div><Link href="/register" className="btn-white">Start for free <ArrowRight size={16}/></Link></div></section><footer className="border-t border-slate-200/80 px-5 py-8 text-sm text-slate-500 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 sm:flex-row"><span>© 2026 SupportPilot AI</span><div className="flex gap-6"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Contact</a></div></div></footer>
</main> }
