"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import {usePathname} from "next/navigation";
import {BarChart3,Bell,BookOpen,CircleDollarSign,Inbox,LayoutDashboard,LogOut,Mail,Menu,Moon,Settings,ShieldCheck,Sparkles,Sun,Users,X} from "lucide-react";
import {useEffect,useState} from "react";
const core=[['/dashboard','Overview',LayoutDashboard],['/dashboard/conversations','Conversations',Inbox],['/dashboard/knowledge','Knowledge Base',BookOpen],['/dashboard/analytics','Analytics',BarChart3],['/dashboard/team','Team',Users],['/dashboard/settings','Settings',Settings]] as const;
const owner=[['/dashboard/billing','Plans & usage',CircleDollarSign],['/dashboard/development-emails','Email outbox',Mail],['/dashboard/system-status','System status',ShieldCheck]] as const;
export function DashboardShell({children,user,workspace,role,publicDemo=false,publicBeta=false}:{children:React.ReactNode;user:{name:string;email:string};workspace:string;role:string;publicDemo?:boolean;publicBeta?:boolean}){const path=usePathname(),[dark,setDark]=useState(false),[open,setOpen]=useState(false),items=role==="OWNER"?[...core,...owner]:core;useEffect(()=>setDark(localStorage.theme==='dark'||(!('theme' in localStorage)&&matchMedia('(prefers-color-scheme: dark)').matches)),[]);useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.theme=dark?'dark':'light'},[dark]);useEffect(()=>setOpen(false),[path]);const initials=user.name.split(" ").map(part=>part[0]).join("").slice(0,2).toUpperCase();return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a>{open&&<button aria-label="Close navigation overlay" className="sidebar-overlay" onClick={()=>setOpen(false)}/>}<aside id="dashboard-navigation" className={`sidebar ${open?"sidebar-open":""}`} aria-label="Dashboard navigation"><div className="flex items-center justify-between"><Link href="/" className="brand"><span className="brand-mark"><Sparkles size={18}/></span>SupportPilot <b>AI</b></Link><button className="icon-button md:hidden" aria-label="Close navigation" onClick={()=>setOpen(false)}><X size={18}/></button></div><nav className="side-nav">{items.map(([href,label,Icon])=><Link key={href} href={href} aria-current={path===href?"page":undefined} className={`nav-link ${path===href?'active':''}`}><Icon size={17}/>{label}</Link>)}</nav><div className="workspace"><div className="avatar">{initials}</div><div><b>{user.name}</b><span>{workspace} · {role.toLowerCase()}</span></div></div></aside><section className="app-main"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" aria-expanded={open} aria-controls="dashboard-navigation" onClick={()=>setOpen(true)}><Menu size={18}/></button><div className="text-sm text-[var(--muted)]">{workspace}</div><div className="top-actions"><button aria-label={`Switch to ${dark?"light":"dark"} theme`} className="icon-button" onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button aria-label="Notifications preview" className="icon-button"><Bell size={17}/></button><form action="/logout" method="post"><button aria-label="Log out" className="icon-button" type="submit"><LogOut size={17}/></button></form></div></header>{publicDemo&&<div className="demo-banner mx-4 mt-4">Public portfolio mode · seeded demonstration data · mock AI · private uploads disabled</div>}{publicBeta&&<div className="demo-banner mx-4 mt-4">Public Beta · isolated workspace · mock AI · Knowledge Base uploads unavailable</div>}<div id="main-content">{children}</div></section></div>}
