import { createHash } from "crypto";
import type { PrismaClient } from "@prisma/client";
import { newAnonymousToken } from "./safety";

const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function getPublicChatbot(db:PrismaClient,publicId:string){return db.chatbotConfig.findFirst({where:{publicId,enabled:true},select:{id:true,publicId:true,workspaceId:true,name:true,welcomeMessage:true,color:true}})}
export async function getOrCreateChatSession(db:PrismaClient,chatbot:{id:string;workspaceId:string},token?:string){if(token){const existing=await db.customerChatSession.findFirst({where:{tokenHash:tokenHash(token),chatbotId:chatbot.id}});if(existing)return{session:existing,token,isNew:false}}const fresh=newAnonymousToken(),anonymousKey=tokenHash(fresh).slice(0,20);const customer=await db.customer.upsert({where:{workspaceId_email:{workspaceId:chatbot.workspaceId,email:`anonymous-${anonymousKey}@chat.supportpilot.local`}},update:{},create:{workspaceId:chatbot.workspaceId,name:"Chat visitor",email:`anonymous-${anonymousKey}@chat.supportpilot.local`}});const conversation=await db.conversation.create({data:{workspaceId:chatbot.workspaceId,customerId:customer.id,subject:"Website support chat"}});const session=await db.customerChatSession.create({data:{workspaceId:chatbot.workspaceId,chatbotId:chatbot.id,conversationId:conversation.id,tokenHash:tokenHash(fresh)}});return{session,token:fresh,isNew:true}}
export async function publicConversation(db:PrismaClient,chatbotId:string,token?:string){if(!token)return null;return db.customerChatSession.findFirst({where:{chatbotId,tokenHash:tokenHash(token)},include:{conversation:{include:{messages:{orderBy:{createdAt:"asc"}},aiResponses:{include:{citations:{include:{chunk:{include:{document:{select:{title:true}}}}}}},orderBy:{createdAt:"asc"}}}}}})}
export async function escalateChat(db:PrismaClient,chatbotId:string,token:string){const session=await db.customerChatSession.findFirst({where:{chatbotId,tokenHash:tokenHash(token)}});if(!session)throw new Error("Chat session not found");await db.$transaction([db.customerChatSession.update({where:{id:session.id},data:{escalatedAt:new Date()}}),db.conversation.update({where:{id:session.conversationId},data:{aiSuspended:true,humanTakeoverAt:new Date()}}),db.activityEvent.create({data:{workspaceId:session.workspaceId,conversationId:session.conversationId,type:"chat.escalated",description:"Customer requested human support"}})])}
