import { AIProviderError, type AIProvider, type ChatRequest, type ChatResult, type EmbeddingResult, type ProviderHealth } from "./types";

type OllamaOptions = { baseUrl:string; chatModel:string; embeddingModel:string; embeddingDimensions:number; timeoutMs?:number };
export class OllamaProvider implements AIProvider {
  readonly name="ollama"; readonly chatModel; readonly embeddingModel; readonly embeddingDimensions; private baseUrl; private timeoutMs;
  constructor(options:OllamaOptions){if(!/^http:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(options.baseUrl))throw new AIProviderError("Ollama must use a loopback URL","CONFIGURATION");this.baseUrl=options.baseUrl.replace(/\/$/,"");this.chatModel=options.chatModel;this.embeddingModel=options.embeddingModel;this.embeddingDimensions=options.embeddingDimensions;this.timeoutMs=options.timeoutMs??45_000}
  private async request(path:string,body:unknown,signal?:AbortSignal){const timeout=AbortSignal.timeout(this.timeoutMs),combined=signal?AbortSignal.any([signal,timeout]):timeout;try{const response=await fetch(`${this.baseUrl}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:combined,cache:"no-store"});if(!response.ok)throw new AIProviderError(`Ollama request failed (${response.status})`,"UNAVAILABLE",true);return response}catch(error){if(error instanceof AIProviderError)throw error;if(combined.aborted)throw new AIProviderError("AI request timed out","TIMEOUT",true);throw new AIProviderError("Local AI is temporarily unavailable","UNAVAILABLE",true)}}
  async chat(input:ChatRequest):Promise<ChatResult>{const started=Date.now(),response=await this.request("/api/chat",{model:this.chatModel,messages:input.messages,stream:false,options:{temperature:input.temperature??0,num_predict:input.maxTokens??500}},input.signal);const json=await response.json() as {message?:{content?:string}};if(!json.message?.content)throw new AIProviderError("Ollama returned an invalid chat response","INVALID_RESPONSE");return{text:json.message.content,model:this.chatModel,durationMs:Date.now()-started}}
  async *stream(input:ChatRequest){const response=await this.request("/api/chat",{model:this.chatModel,messages:input.messages,stream:true,options:{temperature:input.temperature??0,num_predict:input.maxTokens??500}},input.signal);if(!response.body)throw new AIProviderError("Ollama returned no stream","INVALID_RESPONSE");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const json=JSON.parse(line) as {message?:{content?:string}};if(json.message?.content)yield json.message.content}}}
  async embed(inputs:string[],signal?:AbortSignal):Promise<EmbeddingResult>{if(!inputs.length)return{vectors:[],model:this.embeddingModel,dimensions:this.embeddingDimensions};const response=await this.request("/api/embed",{model:this.embeddingModel,input:inputs},signal),json=await response.json() as {embeddings?:number[][]};if(!json.embeddings||json.embeddings.some(v=>v.length!==this.embeddingDimensions))throw new AIProviderError("Embedding dimensions did not match configuration","INVALID_RESPONSE");return{vectors:json.embeddings,model:this.embeddingModel,dimensions:this.embeddingDimensions}}
  async health(signal?:AbortSignal):Promise<ProviderHealth>{try{const response=await fetch(`${this.baseUrl}/api/version`,{signal:signal??AbortSignal.timeout(3000),cache:"no-store"});const json=await response.json() as {version?:string};return{ok:response.ok,provider:this.name,version:json.version}}catch{return{ok:false,provider:this.name,error:"Local AI is unavailable"}}}
}
