import Link from "next/link";
import { notFound } from "next/navigation";
import { deleteDocumentAction, retryDocumentAction, updateDocumentAction } from "@/app/actions/knowledge";
import { PageHead } from "@/components/page-ui";
import { requireWorkspace } from "@/lib/auth";
import { db } from "@/lib/db";
import { getDocument } from "@/lib/knowledge-service";

export default async function KnowledgeDetail({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<Record<string,string|undefined>> }) {
  const [{id}, p] = await Promise.all([params, searchParams]); const { user, workspace, membership } = await requireWorkspace();
  const [document, collections] = await Promise.all([getDocument(db,user.id,workspace.id,id),db.knowledgeCollection.findMany({where:{workspaceId:workspace.id},orderBy:{name:"asc"}})]); if (!document) notFound(); const writable=membership.role!=="VIEWER", isArticle=document.sourceType==="ARTICLE";
  return <main className="page-wrap"><PageHead title={document.title} desc={`${document.sourceType} · ${document.status.toLowerCase()}`}/><Link className="text-sm text-[#6558f5]" href="/dashboard/knowledge">← Back to Knowledge Base</Link>{(p.uploaded||p.created||p.saved)&&<div className="mt-4 rounded-xl border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-800">Knowledge source saved successfully.</div>}{document.failureReason&&<div className="mt-4 rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800"><b>Processing failed:</b> {document.failureReason}</div>}
    <div className="mt-4 grid gap-4 lg:grid-cols-[2fr_1fr]"><section className="panel"><h2 className="text-lg font-semibold">Extracted knowledge</h2><p className="panel-sub">{document.chunks.length} deterministic chunks{document.originalFilename?` from ${document.originalFilename}`:""}</p><div className="mt-5 grid gap-3">{document.chunks.length===0?<div className="empty-state"><p>No extracted text is available.</p></div>:document.chunks.map(c=><article key={c.id} className="rounded-xl border border-[var(--line)] p-4"><div className="mb-2 text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Chunk {c.position+1}{c.pageNumber?` · Page ${c.pageNumber}`:""}{c.section?` · ${c.section}`:""}</div><p className="whitespace-pre-wrap text-sm leading-6">{c.content}</p></article>)}</div></section>
      <aside className="grid content-start gap-4"><section className="panel"><h3 className="font-semibold">Details</h3><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-[var(--muted)]">Collection</dt><dd>{document.collection?.name??"Unfiled"}</dd></div><div><dt className="text-[var(--muted)]">Creator</dt><dd>{document.creator.name}</dd></div><div><dt className="text-[var(--muted)]">Size</dt><dd>{document.fileSize?`${Math.ceil(document.fileSize/1024)} KB`:"Article"}</dd></div><div><dt className="text-[var(--muted)]">Updated</dt><dd>{document.updatedAt.toLocaleString()}</dd></div></dl></section>
      {writable&&<section className="panel"><h3 className="font-semibold">Edit source</h3><form action={updateDocumentAction} className="mt-4 grid gap-3"><input type="hidden" name="documentId" value={document.id}/><input className="filter-input" name="title" required defaultValue={document.title}/><textarea className="filter-input" name="description" defaultValue={document.description??""}/><select className="filter-input" name="collectionId" defaultValue={document.collectionId??""}><option value="">No collection</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{isArticle&&<textarea className="filter-input min-h-56" name="content" required defaultValue={document.chunks.map(c=>c.content).join("\n\n")}/>}<button className="btn-primary">Save changes</button></form>{document.status==="FAILED"&&<form action={retryDocumentAction} className="mt-3"><input type="hidden" name="documentId" value={document.id}/><button className="btn-secondary w-full">Retry processing</button></form>}</section>}
      {membership.role==="OWNER"&&<details className="panel"><summary className="cursor-pointer font-semibold text-red-600">Delete source</summary><form action={deleteDocumentAction} className="mt-4 grid gap-3"><input type="hidden" name="documentId" value={document.id}/><p className="text-sm text-[var(--muted)]">This permanently removes the private file, chunks, jobs, and activity.</p><input className="filter-input" name="confirm" required placeholder="Type DELETE"/><button className="btn-secondary text-red-600">Delete permanently</button></form></details>}</aside></div>
    <section className="panel mt-4"><h2 className="text-lg font-semibold">Activity</h2><div className="mt-4 grid gap-3">{document.activities.map(a=><div key={a.id} className="flex justify-between gap-3 border-b border-[var(--line)] pb-3 text-sm"><span><b>{a.actor?.name??"System"}</b> {a.description}</span><time className="text-[var(--muted)]">{a.createdAt.toLocaleString()}</time></div>)}</div></section></main>;
}
