"use server";
import {db} from "@/lib/db"; import {requireWorkspace,requireUser} from "@/lib/auth"; import * as support from "@/lib/support-service"; import {acceptInvitation,createInvitation} from "@/lib/invitation-service"; import {revalidatePath} from "next/cache"; import {redirect} from "next/navigation"; import {z} from "zod";
const text=z.string().trim().min(1).max(10000),id=z.string().min(1); const status=z.enum(["OPEN","PENDING","RESOLVED"]),priority=z.enum(["LOW","NORMAL","HIGH","URGENT"]),role=z.enum(["OWNER","AGENT","VIEWER"]);
export async function createConversationAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({name:z.string().trim().min(2),email:z.email().toLowerCase(),subject:z.string().trim().min(2),body:text,priority}).safeParse(Object.fromEntries(form));if(!v.success)throw new Error("Please complete all conversation fields correctly");const c=await support.createConversation(db,user.id,workspace.id,v.data);redirect(`/dashboard/conversations/${c.id}`)}
export async function replyAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,body:text,customer:z.string().optional()}).parse(Object.fromEntries(form));await support.addMessage(db,user.id,workspace.id,v.conversationId,v.body,v.customer==="true");revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function updateConversationAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,status:status.optional(),priority:priority.optional()}).parse(Object.fromEntries(form));await support.updateConversation(db,user.id,workspace.id,v.conversationId,{status:v.status,priority:v.priority});revalidatePath(`/dashboard/conversations/${v.conversationId}`);revalidatePath("/dashboard")}
export async function assignAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,agentId:z.string().optional()}).parse(Object.fromEntries(form));await support.assignConversation(db,user.id,workspace.id,v.conversationId,v.agentId||undefined);revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function tagAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,tagId:id,remove:z.string().optional()}).parse(Object.fromEntries(form));await support.setTag(db,user.id,workspace.id,v.conversationId,v.tagId,v.remove==="true");revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function noteAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,body:text}).parse(Object.fromEntries(form));await support.addNote(db,user.id,workspace.id,v.conversationId,v.body);revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function inviteAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"OWNER");const v=z.object({email:z.email().toLowerCase(),role}).parse(Object.fromEntries(form));const result=await createInvitation(db,user.id,workspace.id,v.email,v.role);redirect(process.env.NODE_ENV==="development"?`/dashboard/team?invite=${encodeURIComponent(result.token)}`:"/dashboard/team?invited=1")}
export async function acceptInviteAction(form:FormData){const user=await requireUser();const token=z.string().min(20).parse(form.get("token"));await acceptInvitation(db,user.id,token);redirect("/dashboard")}
