"use server";
import {db} from "@/lib/db"; import {requireWorkspace,requireUser} from "@/lib/auth"; import * as support from "@/lib/support-service"; import {acceptInvitation,createInvitation} from "@/lib/invitation-service"; import {revalidatePath} from "next/cache"; import {redirect} from "next/navigation"; import {z} from "zod"; import {DevelopmentOutboxProvider} from "@/lib/email-provider"; import {validateRuntimeConfig} from "@/lib/runtime-config";
const text=z.string().trim().min(1).max(10000),id=z.string().min(1); const status=z.enum(["OPEN","PENDING","RESOLVED"]),priority=z.enum(["LOW","NORMAL","HIGH","URGENT"]),role=z.enum(["OWNER","AGENT","VIEWER"]);
export async function createConversationAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({name:z.string().trim().min(2),email:z.email().toLowerCase(),subject:z.string().trim().min(2),body:text,priority}).safeParse(Object.fromEntries(form));if(!v.success)throw new Error("Please complete all conversation fields correctly");const c=await support.createConversation(db,user.id,workspace.id,v.data);redirect(`/dashboard/conversations/${c.id}`)}
export async function replyAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,body:text,customer:z.string().optional()}).parse(Object.fromEntries(form));await support.addMessage(db,user.id,workspace.id,v.conversationId,v.body,v.customer==="true");revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function updateConversationAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,status:status.optional(),priority:priority.optional()}).parse(Object.fromEntries(form));await support.updateConversation(db,user.id,workspace.id,v.conversationId,{status:v.status,priority:v.priority});revalidatePath(`/dashboard/conversations/${v.conversationId}`);revalidatePath("/dashboard")}
export async function assignAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT"),runtime=validateRuntimeConfig();const v=z.object({conversationId:id,agentId:z.string().optional()}).parse(Object.fromEntries(form));await support.assignConversation(db,user.id,workspace.id,v.conversationId,v.agentId||undefined);if(v.agentId){const [agent,conversation]=await Promise.all([db.user.findFirst({where:{id:v.agentId,memberships:{some:{workspaceId:workspace.id}}}}),db.conversation.findFirst({where:{id:v.conversationId,workspaceId:workspace.id},select:{subject:true}})]);if(agent&&conversation){const provider=new DevelopmentOutboxProvider(db),queued=await provider.queue({workspaceId:workspace.id,recipientUserId:agent.id,to:agent.email,type:"ASSIGNMENT",subject:`Conversation assigned: ${conversation.subject}`,body:"A conversation was assigned to you in SupportPilot.",actionUrl:`${runtime.baseUrl}/dashboard/conversations/${v.conversationId}`});await provider.deliver(queued.id)}}revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function tagAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,tagId:id,remove:z.string().optional()}).parse(Object.fromEntries(form));await support.setTag(db,user.id,workspace.id,v.conversationId,v.tagId,v.remove==="true");revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function noteAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"AGENT");const v=z.object({conversationId:id,body:text}).parse(Object.fromEntries(form));await support.addNote(db,user.id,workspace.id,v.conversationId,v.body);revalidatePath(`/dashboard/conversations/${v.conversationId}`)}
export async function inviteAction(form:FormData){const {user,workspace}=await requireWorkspace(undefined,"OWNER"),runtime=validateRuntimeConfig();const v=z.object({email:z.email().toLowerCase(),role}).parse(Object.fromEntries(form));const result=await createInvitation(db,user.id,workspace.id,v.email,v.role),provider=new DevelopmentOutboxProvider(db),queued=await provider.queue({workspaceId:workspace.id,to:v.email,type:"INVITATION",subject:`Join ${workspace.name} on SupportPilot`,body:`You were invited as ${v.role.toLowerCase()}. This development-only invitation expires in seven days and can be used once.`,actionUrl:`${runtime.baseUrl}/invitations/${result.token}`});await provider.deliver(queued.id);redirect("/dashboard/team?invited=1")}
export async function acceptInviteAction(form:FormData){const user=await requireUser();const token=z.string().min(20).parse(form.get("token"));await acceptInvitation(db,user.id,token);redirect("/dashboard")}
